# Generated by Django 5.2.15 on 2026-06-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
